# Generated by Django 2.2.1 on 2019-05-21 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
    ]
