# Generated by Django 2.2.1 on 2019-05-22 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='url',
            field=models.TextField(default='https://www.google.com'),
        ),
    ]
