# Generated by Django 2.2.1 on 2019-05-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tag_color',
            field=models.CharField(default='#adb5bd', max_length=7),
        ),
    ]
